- hosts: all
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    size: 4
    greeting: Hello
    meta:
      name: example-hello
      namespace: default
  roles:
    - hello

